name: "flight_dbt"
version: "1.0.0"

profile: flight_dbt

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  flight_dbt:
    marts:
      +materialized: table
    staging:
      +materialized: view
